# coding: utf-8

"""
    Kubeflow Pipelines API

    This file contains REST API specification for Kubeflow Pipelines. The file is autogenerated from the swagger definition.

    Contact: kubeflow-pipelines@google.com
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from kfp_server_api.configuration import Configuration


class ApiPipelineTaskDetail(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'task_id': 'str',
        'run_id': 'str',
        'display_name': 'str',
        'create_time': 'datetime',
        'start_time': 'datetime',
        'end_time': 'datetime',
        'executor_detail': 'ApiPipelineTaskExecutorDetail',
        'state': 'ApiRuntimeState',
        'execution_id': 'str',
        'error': 'ApiError',
        'inputs': 'dict(str, ApiArtifactList)',
        'outputs': 'dict(str, ApiArtifactList)',
        'parent_task_id': 'str',
        'state_history': 'list[ApiRuntimeStatus]'
    }

    attribute_map = {
        'task_id': 'task_id',
        'run_id': 'run_id',
        'display_name': 'display_name',
        'create_time': 'create_time',
        'start_time': 'start_time',
        'end_time': 'end_time',
        'executor_detail': 'executor_detail',
        'state': 'state',
        'execution_id': 'execution_id',
        'error': 'error',
        'inputs': 'inputs',
        'outputs': 'outputs',
        'parent_task_id': 'parent_task_id',
        'state_history': 'state_history'
    }

    def __init__(self, task_id=None, run_id=None, display_name=None, create_time=None, start_time=None, end_time=None, executor_detail=None, state=None, execution_id=None, error=None, inputs=None, outputs=None, parent_task_id=None, state_history=None, local_vars_configuration=None):  # noqa: E501
        """ApiPipelineTaskDetail - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._task_id = None
        self._run_id = None
        self._display_name = None
        self._create_time = None
        self._start_time = None
        self._end_time = None
        self._executor_detail = None
        self._state = None
        self._execution_id = None
        self._error = None
        self._inputs = None
        self._outputs = None
        self._parent_task_id = None
        self._state_history = None
        self.discriminator = None

        if task_id is not None:
            self.task_id = task_id
        if run_id is not None:
            self.run_id = run_id
        if display_name is not None:
            self.display_name = display_name
        if create_time is not None:
            self.create_time = create_time
        if start_time is not None:
            self.start_time = start_time
        if end_time is not None:
            self.end_time = end_time
        if executor_detail is not None:
            self.executor_detail = executor_detail
        if state is not None:
            self.state = state
        if execution_id is not None:
            self.execution_id = execution_id
        if error is not None:
            self.error = error
        if inputs is not None:
            self.inputs = inputs
        if outputs is not None:
            self.outputs = outputs
        if parent_task_id is not None:
            self.parent_task_id = parent_task_id
        if state_history is not None:
            self.state_history = state_history

    @property
    def task_id(self):
        """Gets the task_id of this ApiPipelineTaskDetail.  # noqa: E501

        The system-generated ID of the task.  # noqa: E501

        :return: The task_id of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: str
        """
        return self._task_id

    @task_id.setter
    def task_id(self, task_id):
        """Sets the task_id of this ApiPipelineTaskDetail.

        The system-generated ID of the task.  # noqa: E501

        :param task_id: The task_id of this ApiPipelineTaskDetail.  # noqa: E501
        :type task_id: str
        """

        self._task_id = task_id

    @property
    def run_id(self):
        """Gets the run_id of this ApiPipelineTaskDetail.  # noqa: E501

        The id of the parent Run.  # noqa: E501

        :return: The run_id of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: str
        """
        return self._run_id

    @run_id.setter
    def run_id(self, run_id):
        """Sets the run_id of this ApiPipelineTaskDetail.

        The id of the parent Run.  # noqa: E501

        :param run_id: The run_id of this ApiPipelineTaskDetail.  # noqa: E501
        :type run_id: str
        """

        self._run_id = run_id

    @property
    def display_name(self):
        """Gets the display_name of this ApiPipelineTaskDetail.  # noqa: E501

        The user specified name of the task that is defined in [Pipeline.spec][].  # noqa: E501

        :return: The display_name of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: str
        """
        return self._display_name

    @display_name.setter
    def display_name(self, display_name):
        """Sets the display_name of this ApiPipelineTaskDetail.

        The user specified name of the task that is defined in [Pipeline.spec][].  # noqa: E501

        :param display_name: The display_name of this ApiPipelineTaskDetail.  # noqa: E501
        :type display_name: str
        """

        self._display_name = display_name

    @property
    def create_time(self):
        """Gets the create_time of this ApiPipelineTaskDetail.  # noqa: E501

        Task create time.  # noqa: E501

        :return: The create_time of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this ApiPipelineTaskDetail.

        Task create time.  # noqa: E501

        :param create_time: The create_time of this ApiPipelineTaskDetail.  # noqa: E501
        :type create_time: datetime
        """

        self._create_time = create_time

    @property
    def start_time(self):
        """Gets the start_time of this ApiPipelineTaskDetail.  # noqa: E501

        Task start time.  # noqa: E501

        :return: The start_time of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._start_time

    @start_time.setter
    def start_time(self, start_time):
        """Sets the start_time of this ApiPipelineTaskDetail.

        Task start time.  # noqa: E501

        :param start_time: The start_time of this ApiPipelineTaskDetail.  # noqa: E501
        :type start_time: datetime
        """

        self._start_time = start_time

    @property
    def end_time(self):
        """Gets the end_time of this ApiPipelineTaskDetail.  # noqa: E501

        Task end time.  # noqa: E501

        :return: The end_time of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: datetime
        """
        return self._end_time

    @end_time.setter
    def end_time(self, end_time):
        """Sets the end_time of this ApiPipelineTaskDetail.

        Task end time.  # noqa: E501

        :param end_time: The end_time of this ApiPipelineTaskDetail.  # noqa: E501
        :type end_time: datetime
        """

        self._end_time = end_time

    @property
    def executor_detail(self):
        """Gets the executor_detail of this ApiPipelineTaskDetail.  # noqa: E501


        :return: The executor_detail of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: ApiPipelineTaskExecutorDetail
        """
        return self._executor_detail

    @executor_detail.setter
    def executor_detail(self, executor_detail):
        """Sets the executor_detail of this ApiPipelineTaskDetail.


        :param executor_detail: The executor_detail of this ApiPipelineTaskDetail.  # noqa: E501
        :type executor_detail: ApiPipelineTaskExecutorDetail
        """

        self._executor_detail = executor_detail

    @property
    def state(self):
        """Gets the state of this ApiPipelineTaskDetail.  # noqa: E501


        :return: The state of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: ApiRuntimeState
        """
        return self._state

    @state.setter
    def state(self, state):
        """Sets the state of this ApiPipelineTaskDetail.


        :param state: The state of this ApiPipelineTaskDetail.  # noqa: E501
        :type state: ApiRuntimeState
        """

        self._state = state

    @property
    def execution_id(self):
        """Gets the execution_id of this ApiPipelineTaskDetail.  # noqa: E501

        The execution metadata of the task.  # noqa: E501

        :return: The execution_id of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: str
        """
        return self._execution_id

    @execution_id.setter
    def execution_id(self, execution_id):
        """Sets the execution_id of this ApiPipelineTaskDetail.

        The execution metadata of the task.  # noqa: E501

        :param execution_id: The execution_id of this ApiPipelineTaskDetail.  # noqa: E501
        :type execution_id: str
        """

        self._execution_id = execution_id

    @property
    def error(self):
        """Gets the error of this ApiPipelineTaskDetail.  # noqa: E501


        :return: The error of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: ApiError
        """
        return self._error

    @error.setter
    def error(self, error):
        """Sets the error of this ApiPipelineTaskDetail.


        :param error: The error of this ApiPipelineTaskDetail.  # noqa: E501
        :type error: ApiError
        """

        self._error = error

    @property
    def inputs(self):
        """Gets the inputs of this ApiPipelineTaskDetail.  # noqa: E501

        The runtime input artifacts of the task.  # noqa: E501

        :return: The inputs of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: dict(str, ApiArtifactList)
        """
        return self._inputs

    @inputs.setter
    def inputs(self, inputs):
        """Sets the inputs of this ApiPipelineTaskDetail.

        The runtime input artifacts of the task.  # noqa: E501

        :param inputs: The inputs of this ApiPipelineTaskDetail.  # noqa: E501
        :type inputs: dict(str, ApiArtifactList)
        """

        self._inputs = inputs

    @property
    def outputs(self):
        """Gets the outputs of this ApiPipelineTaskDetail.  # noqa: E501

        The runtime output artifacts of the task.  # noqa: E501

        :return: The outputs of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: dict(str, ApiArtifactList)
        """
        return self._outputs

    @outputs.setter
    def outputs(self, outputs):
        """Sets the outputs of this ApiPipelineTaskDetail.

        The runtime output artifacts of the task.  # noqa: E501

        :param outputs: The outputs of this ApiPipelineTaskDetail.  # noqa: E501
        :type outputs: dict(str, ApiArtifactList)
        """

        self._outputs = outputs

    @property
    def parent_task_id(self):
        """Gets the parent_task_id of this ApiPipelineTaskDetail.  # noqa: E501

        The id of the parent task if the task is within a component scope. Empty if the task is at the root level.  # noqa: E501

        :return: The parent_task_id of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: str
        """
        return self._parent_task_id

    @parent_task_id.setter
    def parent_task_id(self, parent_task_id):
        """Sets the parent_task_id of this ApiPipelineTaskDetail.

        The id of the parent task if the task is within a component scope. Empty if the task is at the root level.  # noqa: E501

        :param parent_task_id: The parent_task_id of this ApiPipelineTaskDetail.  # noqa: E501
        :type parent_task_id: str
        """

        self._parent_task_id = parent_task_id

    @property
    def state_history(self):
        """Gets the state_history of this ApiPipelineTaskDetail.  # noqa: E501

        A list of task statuses. This field keeps a record of task status evolving over time.  # noqa: E501

        :return: The state_history of this ApiPipelineTaskDetail.  # noqa: E501
        :rtype: list[ApiRuntimeStatus]
        """
        return self._state_history

    @state_history.setter
    def state_history(self, state_history):
        """Sets the state_history of this ApiPipelineTaskDetail.

        A list of task statuses. This field keeps a record of task status evolving over time.  # noqa: E501

        :param state_history: The state_history of this ApiPipelineTaskDetail.  # noqa: E501
        :type state_history: list[ApiRuntimeStatus]
        """

        self._state_history = state_history

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ApiPipelineTaskDetail):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ApiPipelineTaskDetail):
            return True

        return self.to_dict() != other.to_dict()
