// Code generated by go-swagger; DO NOT EDIT.

package recurring_run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/validate"
)

// APIRecurringRunStatus Output. The status of the recurring run.
//
//  - STATUS_ENABLING: The recurring run is working on being enabled.
//  - STATUS_DISABLING: The recurring run is working on being disabled.
// swagger:model apiRecurringRunStatus
type APIRecurringRunStatus string

const (

	// APIRecurringRunStatusSTATUSUNSPECIFIED captures enum value "STATUS_UNSPECIFIED"
	APIRecurringRunStatusSTATUSUNSPECIFIED APIRecurringRunStatus = "STATUS_UNSPECIFIED"

	// APIRecurringRunStatusSTATUSENABLED captures enum value "STATUS_ENABLED"
	APIRecurringRunStatusSTATUSENABLED APIRecurringRunStatus = "STATUS_ENABLED"

	// APIRecurringRunStatusSTATUSENABLING captures enum value "STATUS_ENABLING"
	APIRecurringRunStatusSTATUSENABLING APIRecurringRunStatus = "STATUS_ENABLING"

	// APIRecurringRunStatusSTATUSDISABLED captures enum value "STATUS_DISABLED"
	APIRecurringRunStatusSTATUSDISABLED APIRecurringRunStatus = "STATUS_DISABLED"

	// APIRecurringRunStatusSTATUSDISABLING captures enum value "STATUS_DISABLING"
	APIRecurringRunStatusSTATUSDISABLING APIRecurringRunStatus = "STATUS_DISABLING"
)

// for schema
var apiRecurringRunStatusEnum []interface{}

func init() {
	var res []APIRecurringRunStatus
	if err := json.Unmarshal([]byte(`["STATUS_UNSPECIFIED","STATUS_ENABLED","STATUS_ENABLING","STATUS_DISABLED","STATUS_DISABLING"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		apiRecurringRunStatusEnum = append(apiRecurringRunStatusEnum, v)
	}
}

func (m APIRecurringRunStatus) validateAPIRecurringRunStatusEnum(path, location string, value APIRecurringRunStatus) error {
	if err := validate.Enum(path, location, value, apiRecurringRunStatusEnum); err != nil {
		return err
	}
	return nil
}

// Validate validates this api recurring run status
func (m APIRecurringRunStatus) Validate(formats strfmt.Registry) error {
	var res []error

	// value enum
	if err := m.validateAPIRecurringRunStatusEnum("", "body", m); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
