// Code generated by go-swagger; DO NOT EDIT.

package recurring_run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIRuntimeConfig The runtime config.
// swagger:model apiRuntimeConfig
type APIRuntimeConfig struct {

	// The runtime parameters of the Pipeline. The parameters will be
	// used to replace the placeholders at runtime.
	Parameters map[string]interface{} `json:"parameters,omitempty"`

	// A path in a object store bucket which will be treated as the root
	// output directory of the pipeline. It is used by the system to
	// generate the paths of output artifacts.
	// Ref:(https://www.kubeflow.org/docs/components/pipelines/pipeline-root/)
	PipelineRoot string `json:"pipeline_root,omitempty"`
}

// Validate validates this api runtime config
func (m *APIRuntimeConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIRuntimeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRuntimeConfig) UnmarshalBinary(b []byte) error {
	var res APIRuntimeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
