// Code generated by go-swagger; DO NOT EDIT.

package recurring_run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	recurring_run_model "github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/recurring_run_model"
)

// EnableRecurringRunReader is a Reader for the EnableRecurringRun structure.
type EnableRecurringRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *EnableRecurringRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewEnableRecurringRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewEnableRecurringRunDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewEnableRecurringRunOK creates a EnableRecurringRunOK with default headers values
func NewEnableRecurringRunOK() *EnableRecurringRunOK {
	return &EnableRecurringRunOK{}
}

/*EnableRecurringRunOK handles this case with default header values.

A successful response.
*/
type EnableRecurringRunOK struct {
	Payload interface{}
}

func (o *EnableRecurringRunOK) Error() string {
	return fmt.Sprintf("[POST /apis/v2beta1/recurringruns/{recurring_run_id}:enable][%d] enableRecurringRunOK  %+v", 200, o.Payload)
}

func (o *EnableRecurringRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response payload
	if err := consumer.Consume(response.Body(), &o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewEnableRecurringRunDefault creates a EnableRecurringRunDefault with default headers values
func NewEnableRecurringRunDefault(code int) *EnableRecurringRunDefault {
	return &EnableRecurringRunDefault{
		_statusCode: code,
	}
}

/*EnableRecurringRunDefault handles this case with default header values.

EnableRecurringRunDefault enable recurring run default
*/
type EnableRecurringRunDefault struct {
	_statusCode int

	Payload *recurring_run_model.APIStatus
}

// Code gets the status code for the enable recurring run default response
func (o *EnableRecurringRunDefault) Code() int {
	return o._statusCode
}

func (o *EnableRecurringRunDefault) Error() string {
	return fmt.Sprintf("[POST /apis/v2beta1/recurringruns/{recurring_run_id}:enable][%d] EnableRecurringRun default  %+v", o._statusCode, o.Payload)
}

func (o *EnableRecurringRunDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(recurring_run_model.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
