// Code generated by go-swagger; DO NOT EDIT.

package recurring_run_service

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	recurring_run_model "github.com/kubeflow/pipelines/backend/api/v2beta1/go_http_client/recurring_run_model"
)

// GetRecurringRunReader is a Reader for the GetRecurringRun structure.
type GetRecurringRunReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetRecurringRunReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetRecurringRunOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	default:
		result := NewGetRecurringRunDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewGetRecurringRunOK creates a GetRecurringRunOK with default headers values
func NewGetRecurringRunOK() *GetRecurringRunOK {
	return &GetRecurringRunOK{}
}

/*GetRecurringRunOK handles this case with default header values.

A successful response.
*/
type GetRecurringRunOK struct {
	Payload *recurring_run_model.APIRecurringRun
}

func (o *GetRecurringRunOK) Error() string {
	return fmt.Sprintf("[GET /apis/v2beta1/recurringruns/{recurring_run_id}][%d] getRecurringRunOK  %+v", 200, o.Payload)
}

func (o *GetRecurringRunOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(recurring_run_model.APIRecurringRun)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetRecurringRunDefault creates a GetRecurringRunDefault with default headers values
func NewGetRecurringRunDefault(code int) *GetRecurringRunDefault {
	return &GetRecurringRunDefault{
		_statusCode: code,
	}
}

/*GetRecurringRunDefault handles this case with default header values.

GetRecurringRunDefault get recurring run default
*/
type GetRecurringRunDefault struct {
	_statusCode int

	Payload *recurring_run_model.APIStatus
}

// Code gets the status code for the get recurring run default response
func (o *GetRecurringRunDefault) Code() int {
	return o._statusCode
}

func (o *GetRecurringRunDefault) Error() string {
	return fmt.Sprintf("[GET /apis/v2beta1/recurringruns/{recurring_run_id}][%d] GetRecurringRun default  %+v", o._statusCode, o.Payload)
}

func (o *GetRecurringRunDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(recurring_run_model.APIStatus)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
