// Code generated by go-swagger; DO NOT EDIT.

package job_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIPipelineSpecRuntimeConfig The runtime config of a PipelineSpec.
// swagger:model apiPipelineSpecRuntimeConfig
type APIPipelineSpecRuntimeConfig struct {

	// The runtime parameters of the PipelineSpec. The parameters will be
	// used to replace the placeholders
	// at runtime.
	Parameters map[string]interface{} `json:"parameters,omitempty"`

	// A path in a object store bucket which will be treated as the root
	// output directory of the pipeline. It is used by the system to
	// generate the paths of output artifacts. Ref:(https://www.kubeflow.org/docs/components/pipelines/pipeline-root/)
	PipelineRoot string `json:"pipeline_root,omitempty"`
}

// Validate validates this api pipeline spec runtime config
func (m *APIPipelineSpecRuntimeConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIPipelineSpecRuntimeConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPipelineSpecRuntimeConfig) UnmarshalBinary(b []byte) error {
	var res APIPipelineSpecRuntimeConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
