apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  labels:
    app: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      serviceAccountName: mysql
      containers:
      # https://dev.mysql.com/doc/refman/5.7/en/server-options.html#option_mysqld_ignore-db-dir
      # Ext4, Btrfs etc. volumes root directories have a lost+found directory that should not be treated as a database.
      # ignore-db-dir option has been deprecated in mysql v5.7.16.
      #
      # In order to upgrade MySQL to v8.0 remove /var/lib/mysql/lost+found folder in mysql-pv-claim 
      # (mysql-persistent-storage):
      #
      # kubectl exec -it <mysql-pod-name> -n kubeflow -- bash
      # rm -rf /var/lib/mysql/lost+found
      #
      # More details on upgrading MySQL can be found here:
      # https://dev.mysql.com/doc/refman/8.0/en/upgrade-prerequisites.html
      # https://dev.mysql.com/doc/refman/8.0/en/upgrade-docker-mysql.html
      - args:
        - --datadir
        - /var/lib/mysql
        - --default-authentication-plugin=mysql_native_password
        env:
        - name: MYSQL_ALLOW_EMPTY_PASSWORD
          value: "true"
        image: gcr.io/ml-pipeline/mysql:8.0.26
        name: mysql
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - mountPath: /var/lib/mysql
          name: mysql-persistent-storage
        resources:
            requests:
              cpu: 100m
              memory: 800Mi
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
