// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIPipelineTaskExecutorDetail The runtime detail of a PipelineTask executor.
// swagger:model apiPipelineTaskExecutorDetail
type APIPipelineTaskExecutorDetail struct {

	// The detailed info for a container executor.
	ContainerDetail *PipelineTaskExecutorDetailContainerDetail `json:"container_detail,omitempty"`

	// The detailed info for a custom job executor.
	CustomJobDetail *PipelineTaskExecutorDetailCustomJobDetail `json:"custom_job_detail,omitempty"`
}

// Validate validates this api pipeline task executor detail
func (m *APIPipelineTaskExecutorDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateContainerDetail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateCustomJobDetail(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIPipelineTaskExecutorDetail) validateContainerDetail(formats strfmt.Registry) error {

	if swag.IsZero(m.ContainerDetail) { // not required
		return nil
	}

	if m.ContainerDetail != nil {
		if err := m.ContainerDetail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("container_detail")
			}
			return err
		}
	}

	return nil
}

func (m *APIPipelineTaskExecutorDetail) validateCustomJobDetail(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomJobDetail) { // not required
		return nil
	}

	if m.CustomJobDetail != nil {
		if err := m.CustomJobDetail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("custom_job_detail")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIPipelineTaskExecutorDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPipelineTaskExecutorDetail) UnmarshalBinary(b []byte) error {
	var res APIPipelineTaskExecutorDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
