// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// MlMetadataValue A value in properties.
// swagger:model ml_metadataValue
type MlMetadataValue struct {

	// double value
	DoubleValue float64 `json:"double_value,omitempty"`

	// int value
	IntValue string `json:"int_value,omitempty"`

	// string value
	StringValue string `json:"string_value,omitempty"`

	// struct value
	StructValue interface{} `json:"struct_value,omitempty"`
}

// Validate validates this ml metadata value
func (m *MlMetadataValue) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *MlMetadataValue) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MlMetadataValue) UnmarshalBinary(b []byte) error {
	var res MlMetadataValue
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
