// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MlMetadataContext ml metadata context
// swagger:model ml_metadataContext
type MlMetadataContext struct {

	// Output only. Create time of the context in millisecond since epoch.
	// Read Only: true
	CreateTimeSinceEpoch string `json:"create_time_since_epoch,omitempty"`

	// User provided custom properties which are not defined by its type.
	CustomProperties map[string]MlMetadataValue `json:"custom_properties,omitempty"`

	// Output Only. The globally unique server generated id of the context.
	ID string `json:"id,omitempty"`

	// Output only. Last update time of the context in millisecond since epoch.
	// Read Only: true
	LastUpdateTimeSinceEpoch string `json:"last_update_time_since_epoch,omitempty"`

	// The client provided name of the context. It must be unique within a
	// database instance.
	Name string `json:"name,omitempty"`

	// Values of the properties, which must be specified in the ContextType.
	Properties map[string]MlMetadataValue `json:"properties,omitempty"`

	// Output only. The name of a ContextType.
	// Read Only: true
	Type string `json:"type,omitempty"`

	// The id of a ContextType. This needs to be specified when a context is
	// created, and it cannot be changed.
	TypeID string `json:"type_id,omitempty"`
}

// Validate validates this ml metadata context
func (m *MlMetadataContext) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProperties(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MlMetadataContext) validateCustomProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomProperties) { // not required
		return nil
	}

	for k := range m.CustomProperties {

		if err := validate.Required("custom_properties"+"."+k, "body", m.CustomProperties[k]); err != nil {
			return err
		}
		if val, ok := m.CustomProperties[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *MlMetadataContext) validateProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.Properties) { // not required
		return nil
	}

	for k := range m.Properties {

		if err := validate.Required("properties"+"."+k, "body", m.Properties[k]); err != nil {
			return err
		}
		if val, ok := m.Properties[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *MlMetadataContext) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MlMetadataContext) UnmarshalBinary(b []byte) error {
	var res MlMetadataContext
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
