// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// MlMetadataArtifact ml metadata artifact
// swagger:model ml_metadataArtifact
type MlMetadataArtifact struct {

	// Output only. Create time of the artifact in millisecond since epoch.
	// Read Only: true
	CreateTimeSinceEpoch string `json:"create_time_since_epoch,omitempty"`

	// User provided custom properties which are not defined by its type.
	CustomProperties map[string]MlMetadataValue `json:"custom_properties,omitempty"`

	// Output only. The globally unique server generated id of the artifact.
	// Read Only: true
	ID string `json:"id,omitempty"`

	// Output only. Last update time of the artifact since epoch in millisecond
	// since epoch.
	// Read Only: true
	LastUpdateTimeSinceEpoch string `json:"last_update_time_since_epoch,omitempty"`

	// The client provided name of the artifact. This field is optional. If set,
	// it must be unique among all the artifacts of the same artifact type within
	// a database instance and cannot be changed once set.
	Name string `json:"name,omitempty"`

	// Properties of the artifact.
	// Properties must be specified in the ArtifactType.
	Properties map[string]MlMetadataValue `json:"properties,omitempty"`

	// The state of the artifact known to the system.
	State MlMetadataArtifactState `json:"state,omitempty"`

	// Output only. The name of an ArtifactType.
	// Read Only: true
	Type string `json:"type,omitempty"`

	// The id of an ArtifactType. This needs to be specified when an artifact is
	// created, and it cannot be changed.
	TypeID string `json:"type_id,omitempty"`

	// The uniform resource identifier of the physical artifact.
	// May be empty if there is no physical artifact.
	URI string `json:"uri,omitempty"`
}

// Validate validates this ml metadata artifact
func (m *MlMetadataArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCustomProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateProperties(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *MlMetadataArtifact) validateCustomProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.CustomProperties) { // not required
		return nil
	}

	for k := range m.CustomProperties {

		if err := validate.Required("custom_properties"+"."+k, "body", m.CustomProperties[k]); err != nil {
			return err
		}
		if val, ok := m.CustomProperties[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *MlMetadataArtifact) validateProperties(formats strfmt.Registry) error {

	if swag.IsZero(m.Properties) { // not required
		return nil
	}

	for k := range m.Properties {

		if err := validate.Required("properties"+"."+k, "body", m.Properties[k]); err != nil {
			return err
		}
		if val, ok := m.Properties[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *MlMetadataArtifact) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *MlMetadataArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MlMetadataArtifact) UnmarshalBinary(b []byte) error {
	var res MlMetadataArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
