// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// APIPipelineTaskDetail The runtime detail of a task execution.
// swagger:model apiPipelineTaskDetail
type APIPipelineTaskDetail struct {

	// Task create time.
	// Format: date-time
	CreateTime strfmt.DateTime `json:"create_time,omitempty"`

	// The user specified name of the task that is defined in
	// [Pipeline.spec][].
	DisplayName string `json:"display_name,omitempty"`

	// Task end time.
	// Format: date-time
	EndTime strfmt.DateTime `json:"end_time,omitempty"`

	// The error that occurred during task execution.
	// Only populated when the task's state is FAILED or CANCELED.
	Error *APIError `json:"error,omitempty"`

	// The execution metadata of the task.
	ExecutionID string `json:"execution_id,omitempty"`

	// The detailed execution info.
	ExecutorDetail *APIPipelineTaskExecutorDetail `json:"executor_detail,omitempty"`

	// The runtime input artifacts of the task.
	Inputs map[string]APIArtifactList `json:"inputs,omitempty"`

	// The runtime output artifacts of the task.
	Outputs map[string]APIArtifactList `json:"outputs,omitempty"`

	// The id of the parent task if the task is within a component scope.
	// Empty if the task is at the root level.
	ParentTaskID string `json:"parent_task_id,omitempty"`

	// The id of the parent Run.
	RunID string `json:"run_id,omitempty"`

	// Task start time.
	// Format: date-time
	StartTime strfmt.DateTime `json:"start_time,omitempty"`

	// State of the task.
	State APIRuntimeState `json:"state,omitempty"`

	// A list of task statuses. This field keeps a record of task status evolving
	// over time.
	StateHistory []*APIRuntimeStatus `json:"state_history"`

	// The system generated ID of the task.
	TaskID string `json:"task_id,omitempty"`
}

// Validate validates this api pipeline task detail
func (m *APIPipelineTaskDetail) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreateTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateExecutorDetail(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateInputs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateOutputs(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStartTime(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateState(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateStateHistory(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIPipelineTaskDetail) validateCreateTime(formats strfmt.Registry) error {

	if swag.IsZero(m.CreateTime) { // not required
		return nil
	}

	if err := validate.FormatOf("create_time", "body", "date-time", m.CreateTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateEndTime(formats strfmt.Registry) error {

	if swag.IsZero(m.EndTime) { // not required
		return nil
	}

	if err := validate.FormatOf("end_time", "body", "date-time", m.EndTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateError(formats strfmt.Registry) error {

	if swag.IsZero(m.Error) { // not required
		return nil
	}

	if m.Error != nil {
		if err := m.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("error")
			}
			return err
		}
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateExecutorDetail(formats strfmt.Registry) error {

	if swag.IsZero(m.ExecutorDetail) { // not required
		return nil
	}

	if m.ExecutorDetail != nil {
		if err := m.ExecutorDetail.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("executor_detail")
			}
			return err
		}
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateInputs(formats strfmt.Registry) error {

	if swag.IsZero(m.Inputs) { // not required
		return nil
	}

	for k := range m.Inputs {

		if err := validate.Required("inputs"+"."+k, "body", m.Inputs[k]); err != nil {
			return err
		}
		if val, ok := m.Inputs[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *APIPipelineTaskDetail) validateOutputs(formats strfmt.Registry) error {

	if swag.IsZero(m.Outputs) { // not required
		return nil
	}

	for k := range m.Outputs {

		if err := validate.Required("outputs"+"."+k, "body", m.Outputs[k]); err != nil {
			return err
		}
		if val, ok := m.Outputs[k]; ok {
			if err := val.Validate(formats); err != nil {
				return err
			}
		}

	}

	return nil
}

func (m *APIPipelineTaskDetail) validateStartTime(formats strfmt.Registry) error {

	if swag.IsZero(m.StartTime) { // not required
		return nil
	}

	if err := validate.FormatOf("start_time", "body", "date-time", m.StartTime.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateState(formats strfmt.Registry) error {

	if swag.IsZero(m.State) { // not required
		return nil
	}

	if err := m.State.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("state")
		}
		return err
	}

	return nil
}

func (m *APIPipelineTaskDetail) validateStateHistory(formats strfmt.Registry) error {

	if swag.IsZero(m.StateHistory) { // not required
		return nil
	}

	for i := 0; i < len(m.StateHistory); i++ {
		if swag.IsZero(m.StateHistory[i]) { // not required
			continue
		}

		if m.StateHistory[i] != nil {
			if err := m.StateHistory[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("state_history" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIPipelineTaskDetail) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIPipelineTaskDetail) UnmarshalBinary(b []byte) error {
	var res APIPipelineTaskDetail
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
