// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// APIRuntimeDetails The runtime details of a Run.
// swagger:model apiRuntimeDetails
type APIRuntimeDetails struct {

	// The context id of the pipeline.
	PipelineContextID string `json:"pipeline_context_id,omitempty"`

	// The context id of the current Run.
	PipelineRunContextID string `json:"pipeline_run_context_id,omitempty"`

	// The runtime details of the tasks under the Run.
	TaskDetails []*APIPipelineTaskDetail `json:"task_details"`
}

// Validate validates this api runtime details
func (m *APIRuntimeDetails) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTaskDetails(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *APIRuntimeDetails) validateTaskDetails(formats strfmt.Registry) error {

	if swag.IsZero(m.TaskDetails) { // not required
		return nil
	}

	for i := 0; i < len(m.TaskDetails); i++ {
		if swag.IsZero(m.TaskDetails[i]) { // not required
			continue
		}

		if m.TaskDetails[i] != nil {
			if err := m.TaskDetails[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("task_details" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *APIRuntimeDetails) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIRuntimeDetails) UnmarshalBinary(b []byte) error {
	var res APIRuntimeDetails
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
