// Code generated by go-swagger; DO NOT EDIT.

package run_model

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// APIArtifactList A list of artifact metadata.
// swagger:model apiArtifactList
type APIArtifactList struct {

	// A list of artifact metadata ids.
	ArtifactIds []string `json:"artifact_ids"`
}

// Validate validates this api artifact list
func (m *APIArtifactList) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *APIArtifactList) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *APIArtifactList) UnmarshalBinary(b []byte) error {
	var res APIArtifactList
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
